version: 2

sources:
  - name: main  # ← ім'я схеми (в DuckDB це `main`)
    tables:
#      - name: raw_customers
#        description: "Raw customer data loaded from MinIO via Airflow DAG"
      - name: raw_sales
        description: "Raw sales data loaded from MinIO via Airflow DAG"
