version: 2

seeds:
  - name: raw_categories
    description: Seed table fsor raw_categories
    columns:
      - name: categoryID
        tests:
          - not_null
      - name: categoryName
        tests:
          - not_null

  - name: raw_cities
    description: Seed table for raw_citiess
    columns:
      - name: CityID
        tests:
          - not_null
      - name: CityName
        tests:
          - not_null
      - name: Zipcode
        tests:
          - not_null
      - name: CountryID
        tests:
          - not_null

  - name: raw_countries
    description: Seed table for raw_countries
    columns:
      - name: CountryID
        tests:
          - not_null
      - name: CountryName
        tests:
          - not_null
      - name: CountryCode
        tests:
          - not_null

#  - name: raw_customers

  - name: raw_employees
    description: Seed table for raw_employees
    columns:
      - name: EmployeeID
        tests:
          - not_null
      - name: FirstName
        tests:
          - not_null
      - name: MiddleInitial
        tests:
          - not_null
      - name: LastName
        tests:
          - not_null
      - name: BirthDate
        tests:
          - not_null
      - name: Gender
        tests:
          - not_null
      - name: CityID
        tests:
          - not_null
      - name: HireDate
        tests:
          - not_null

  - name: raw_products
    description: Seed table for raw_products
    columns:
      - name: ProductID
        tests:
          - not_null
      - name: ProductName
        tests:
          - not_null
      - name: Price
        tests:
          - not_null
      - name: CategoryID
        tests:
          - not_null
      - name: Class
        tests:
          - not_null
      - name: ModifyDate
        tests:
          - not_null
      - name: Resistant
        tests:
          - not_null
      - name: IsAllergic
        tests:
          - not_null
      - name: VitalityDays
        tests:
          - not_null

#  - name: raw_sales
#    description: Seed table for raw_sales
#    columns:
#      - name: SalesID
#        tests:
#          - not_null
#      - name: SalesPersonID
#        tests:
#          - not_null
#      - name: CustomerID
#        tests:
#          - not_null
#      - name: ProductID
#        tests:
#          - not_null
#      - name: Quantity
#        tests:
#          - not_null
#      - name: Discount
#        tests:
#          - not_null
#      - name: TotalPrice
#        tests:
#          - not_null
#      - name: SalesDate
##        tests:
##          - not_null
#      - name: TransactionNumber
#        tests:
#          - not_null
